name:                generic-persistence
version:             0.3.0.0
github:              "thma/generic-persistence"
license:             BSD3
author:              "Thomas Mahler"
maintainer:          "thma@apache.org"
copyright:           "2023 Thomas Mahler"
category:            Database
synopsis:            Database persistence using generics

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thma/generic-persistence#readme>

language: GHC2021    # See https://ghc-proposals.readthedocs.io/en/latest/proposals/0380-ghc2021.html
tested-with: GHC==9.2.5, GHC==9.4.4

dependencies:
- base >= 4.7 && < 5
- convertible
- HDBC #>= 2.4.0.4


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  generic-persistence-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generic-persistence
    - HDBC-sqlite3 #>= 2.3.3.1

tests:
  generic-persistence-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generic-persistence
    - hspec
    - hspec-discover
    - QuickCheck
    - HDBC-sqlite3 #>= 2.3.3.1
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover == 2.*